cube_1:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-1: { ansible_host: 141.100.42.11 }
    pi-2.cube_1: { ansible_host: 141.100.42.12 }
    pi-3.cube-1: { ansible_host: 141.100.42.13 }
    pi-4.cube-1: { ansible_host: 141.100.42.14 }
    pi-5.cube-1: { ansible_host: 141.100.42.15 }
    pi-6.cube-1: { ansible_host: 141.100.42.16 }
    pi-7.cube-1: { ansible_host: 141.100.42.17 }

cube_2:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-2: { ansible_host: 141.100.42.21 }
    pi-2.cube-2: { ansible_host: 141.100.42.22 }
    pi-3.cube-2: { ansible_host: 141.100.42.23 }
    pi-4.cube-2: { ansible_host: 141.100.42.24 }
    pi-5.cube-2: { ansible_host: 141.100.42.25 }
    pi-6.cube-2: { ansible_host: 141.100.42.26 }
    pi-7.cube-2: { ansible_host: 141.100.42.27 }

cube_3:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-3: { ansible_host: 141.100.42.31 }
    pi-2.cube-3: { ansible_host: 141.100.42.32 }
    pi-3.cube-3: { ansible_host: 141.100.42.33 }
    pi-4.cube-3: { ansible_host: 141.100.42.34 }
    pi-5.cube-3: { ansible_host: 141.100.42.35 }
    pi-6.cube-3: { ansible_host: 141.100.42.36 }
    pi-7.cube-3: { ansible_host: 141.100.42.37 }

cube_4:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-4: { ansible_host: 141.100.42.41 }
    pi-2.cube-4: { ansible_host: 141.100.42.42 }
    pi-3.cube-4: { ansible_host: 141.100.42.43 }
    pi-4.cube-4: { ansible_host: 141.100.42.44 }
    pi-5.cube-4: { ansible_host: 141.100.42.45 }
    pi-6.cube-4: { ansible_host: 141.100.42.46 }
    pi-7.cube-4: { ansible_host: 141.100.42.47 }

cube_5:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-5: { ansible_host: 141.100.42.51 }
    pi-2.cube-5: { ansible_host: 141.100.42.52 }
    pi-3.cube-5: { ansible_host: 141.100.42.53 }
    pi-4.cube-5: { ansible_host: 141.100.42.54 }
    pi-5.cube-5: { ansible_host: 141.100.42.55 }
    pi-6.cube-5: { ansible_host: 141.100.42.56 }
    pi-7.cube-5: { ansible_host: 141.100.42.57 }

cube_6:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-6: { ansible_host: 141.100.42.61 }
    pi-2.cube-6: { ansible_host: 141.100.42.62 }
    pi-3.cube-6: { ansible_host: 141.100.42.63 }
    pi-4.cube-6: { ansible_host: 141.100.42.64 }
    pi-5.cube-6: { ansible_host: 141.100.42.65 }
    pi-6.cube-6: { ansible_host: 141.100.42.66 }
    pi-7.cube-6: { ansible_host: 141.100.42.67 }

cube_7:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-7: { ansible_host: 141.100.42.71 }
    pi-2.cube-7: { ansible_host: 141.100.42.72 }
    pi-3.cube-7: { ansible_host: 141.100.42.73 }
    pi-4.cube-7: { ansible_host: 141.100.42.74 }
    pi-5.cube-7: { ansible_host: 141.100.42.75 }
    pi-6.cube-7: { ansible_host: 141.100.42.76 }
    pi-7.cube-7: { ansible_host: 141.100.42.77 }

cube_8:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-8: { ansible_host: 141.100.42.81 }
    pi-2.cube-8: { ansible_host: 141.100.42.82 }
    pi-3.cube-8: { ansible_host: 141.100.42.83 }
    pi-4.cube-8: { ansible_host: 141.100.42.84 }
    pi-5.cube-8: { ansible_host: 141.100.42.85 }
    pi-6.cube-8: { ansible_host: 141.100.42.86 }
    pi-7.cube-8: { ansible_host: 141.100.42.87 }

cube_9:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-9: { ansible_host: 141.100.42.91 }
    pi-2.cube-9: { ansible_host: 141.100.42.92 }
    pi-3.cube-9: { ansible_host: 141.100.42.93 }
    pi-4.cube-9: { ansible_host: 141.100.42.94 }
    pi-5.cube-9: { ansible_host: 141.100.42.95 }
    pi-6.cube-9: { ansible_host: 141.100.42.96 }
    pi-7.cube-9: { ansible_host: 141.100.42.97 }

cube_10:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-10: { ansible_host: 141.100.42.101 }
    pi-2.cube-10: { ansible_host: 141.100.42.102 }
    pi-3.cube-10: { ansible_host: 141.100.42.103 }
    pi-4.cube-10: { ansible_host: 141.100.42.104 }
    pi-5.cube-10: { ansible_host: 141.100.42.105 }
    pi-6.cube-10: { ansible_host: 141.100.42.106 }
    pi-7.cube-10: { ansible_host: 141.100.42.107 }

cube_11:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-11: { ansible_host: 141.100.42.111 }
    pi-2.cube-11: { ansible_host: 141.100.42.112 }
    pi-3.cube-11: { ansible_host: 141.100.42.113 }
    pi-4.cube-11: { ansible_host: 141.100.42.114 }
    pi-5.cube-11: { ansible_host: 141.100.42.115 }
    pi-6.cube-11: { ansible_host: 141.100.42.116 }
    pi-7.cube-11: { ansible_host: 141.100.42.117 }

cube_12:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-12: { ansible_host: 141.100.42.121 }
    pi-2.cube-12: { ansible_host: 141.100.42.122 }
    pi-3.cube-12: { ansible_host: 141.100.42.123 }
    pi-4.cube-12: { ansible_host: 141.100.42.124 }
    pi-5.cube-12: { ansible_host: 141.100.42.125 }
    pi-6.cube-12: { ansible_host: 141.100.42.126 }
    pi-7.cube-12: { ansible_host: 141.100.42.127 }

cube_13:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-13: { ansible_host: 141.100.42.131 }
    pi-2.cube-13: { ansible_host: 141.100.42.132 }
    pi-3.cube-13: { ansible_host: 141.100.42.133 }
    pi-4.cube-13: { ansible_host: 141.100.42.134 }
    pi-5.cube-13: { ansible_host: 141.100.42.135 }
    pi-6.cube-13: { ansible_host: 141.100.42.136 }
    pi-7.cube-13: { ansible_host: 141.100.42.137 }

cube_14:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-14: { ansible_host: 141.100.42.141 }
    pi-2.cube-14: { ansible_host: 141.100.42.142 }
    pi-3.cube-14: { ansible_host: 141.100.42.143 }
    pi-4.cube-14: { ansible_host: 141.100.42.144 }
    pi-5.cube-14: { ansible_host: 141.100.42.145 }
    pi-6.cube-14: { ansible_host: 141.100.42.146 }
    pi-7.cube-14: { ansible_host: 141.100.42.147 }

cube_15:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
  hosts:
    pi-1.cube-15: { ansible_host: 141.100.42.151 }
    pi-2.cube-15: { ansible_host: 141.100.42.152 }
    pi-3.cube-15: { ansible_host: 141.100.42.153 }
    pi-4.cube-15: { ansible_host: 141.100.42.154 }
    pi-5.cube-15: { ansible_host: 141.100.42.155 }
    pi-6.cube-15: { ansible_host: 141.100.42.156 }
    pi-7.cube-15: { ansible_host: 141.100.42.157 }

# All cubes in D14/3.10
lab:
  children:
    cube_1:
    cube_3:
    cube_4:
    cube_7:
    cube_10:
    cube_11:
    cube_12:
    cube_13:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev'
