---
- name: Configure network settings for cube_12
  hosts: cube_12
  become: yes
  vars:
    app_dir: /home/stanbraeh/iot-platform

  tasks:
    - name: Create custom Docker network
      community.docker.docker_network:
        name: iot_platform_net
        state: present
        driver: bridge 