hazelcast:
  cluster-name: dev
  network:
    port:
      port: 5701
      auto-increment: true
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - hazelcast-node
    interfaces:
      enabled: false
  jet:
    enabled: true
  map:
    default:
      backup-count: 1
